# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-MD4
version:      1.5
version_from: MD4.pm
installdirs:  perl
requires:
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
